# Generated by Django 3.1.7 on 2021-03-28 06:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='User', max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='M', max_length=6, null=True)),
                ('image', models.URLField(default='https://firebasestorage.googleapis.com/v0/b/duo-louge.appspot.com/o/user_default.png?alt=media&token=a27eb92b-8292-4e0c-84d3-5db84b1b18d0', null=True)),
                ('age', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('bmi', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('max_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('game_life', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('nutrition', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
