# Generated by Django 3.1.7 on 2021-03-28 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNutritions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('protein', models.CharField(blank=True, max_length=20, null=True)),
                ('carbs', models.CharField(blank=True, max_length=20, null=True)),
                ('fats', models.CharField(blank=True, max_length=20, null=True)),
                ('food_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
